version: "3.6"
services:
  node:
    image: logionnetwork/logion-node:latest
    ports:
      - 9944:9944
    environment:
      - CHAIN_SPEC=dev
      - NODE_KEY=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - CUSTOM_OPTIONS=--alice --rpc-external
